# Generated by Django 5.2.1 on 2025-05-11 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2025, 5, 11))),
                ('category', models.CharField(default='Unknown', max_length=100)),
                ('itemname', models.CharField(default='Unknown', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
