# Generated by Django 5.2.1 on 2025-05-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data',
            new_name='Transaction_data',
        ),
    ]
