# Generated by Django 5.2.1 on 2025-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_data_transaction_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_data',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='itemname',
            field=models.CharField(max_length=200),
        ),
    ]
