# Generated by Django 5.2.1 on 2025-05-11 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_data_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('income', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date(2025, 5, 11))),
            ],
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
