# Generated by Django 5.2.1 on 2025-05-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_alter_transaction_data_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Income',
        ),
    ]
