# Generated by Django 5.2.1 on 2025-05-12 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 12)),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 12, 6, 22, 44, 564330, tzinfo=datetime.timezone.utc)),
        ),
    ]
