# Generated by Django 5.2.1 on 2025-05-12 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_income_date_alter_transaction_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 12, 6, 24, 46, 651153, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 12, 6, 24, 46, 650861, tzinfo=datetime.timezone.utc)),
        ),
    ]
