# Generated by Django 5.2.1 on 2025-05-19 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_income_date_alter_transaction_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 19, 9, 6, 53, 729245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 19)),
        ),
    ]
