# Generated by Django 5.2.1 on 2025-05-21 11:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_income_date_alter_transaction_data_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
