# Generated by Django 5.2.1 on 2025-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_income_date_alter_transaction_data_date_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
