# Generated by Django 5.2.1 on 2025-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_budget_category_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
