# Generated by Django 5.2.1 on 2025-05-27 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 27)),
        ),
    ]
