# Generated by Django 5.2.1 on 2025-05-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_user_id_budget_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction_data',
            old_name='user_id',
            new_name='user',
        ),
    ]
