# Generated by Django 5.2.1 on 2025-05-29 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_budget_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringbills',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='recurringbills',
            name='itemname',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='category',
            field=models.CharField(default='recurring_bill', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
    ]
