# Generated by Django 5.2.1 on 2025-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_amount_recurringbills_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='itemname',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
