# Generated by Django 5.2.1 on 2025-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbills',
            name='date',
            field=models.DateField(default=29),
        ),
    ]
