# Generated by Django 5.2.1 on 2025-05-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_recurringbills_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbills',
            name='date',
            field=models.PositiveIntegerField(default=29),
        ),
    ]
