# Generated by Django 5.2.1 on 2025-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_recurringbills_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbills',
            name='date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='itemname',
            field=models.CharField(default='unknown'),
        ),
    ]
