# Generated by Django 5.2.1 on 2025-05-30 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_budget_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_data',
            name='category',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 30)),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='itemname',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
    ]
