# Generated by Django 5.2.1 on 2025-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_transaction_data_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_data',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='itemname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
