# Generated by Django 5.2.1 on 2025-05-30 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_transaction_data_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='itemname',
            field=models.CharField(default='recurring_bill'),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 30)),
        ),
    ]
