# Generated by Django 5.2.1 on 2025-06-04 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_recurringbills_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_data',
            name='transaction_type',
            field=models.CharField(default='test', max_length=8),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 4)),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='itemname',
            field=models.CharField(default='recurring_bill', max_length=14),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 4)),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
