# Generated by Django 5.2.1 on 2025-06-04 13:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_transaction_data_transaction_type_alter_budget_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=api.models.get_date),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='date',
            field=models.DateField(default=api.models.get_date),
        ),
    ]
