# Generated by Django 5.2.1 on 2025-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_budget_date_alter_transaction_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_data',
            name='transaction_type',
            field=models.CharField(max_length=8),
        ),
    ]
