# Generated by Django 5.2.2 on 2025-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_recurringbills_date_alter_recurringbills_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbills',
            name='date',
            field=models.PositiveIntegerField(),
        ),
    ]
