# Generated by Django 5.2.1 on 2025-07-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_recurringbills_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recurringbills',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='itemname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
